import { describe, expect, it, vi } from "vitest"
import { PalmThunderEngine } from "./engine"
import type { TrackedHand } from "./types"

const tracked = (id: 1 | 2, x: number, y: number): TrackedHand => ({ id, center: { x, y }, box: { x1: 0, y1: 0, x2: 10, y2: 10 }, gesture: "open", gestureProgress: 0, handedness: id === 1 ? "left" : "right", active: true, updatedAt: 0 })

describe("Palm Thunder engine", () => {
  it("places only preselected fighters exactly at their palm centers", () => { const engine = new PalmThunderEngine(1000, 700); engine.configurePlayers(1); engine.setHands([tracked(1, .21, .74), tracked(2, .82, .42)]); expect(engine.state.players[0]).toMatchObject({ x: .21, y: .74, joined: true }); expect(engine.state.players[1]).toMatchObject({ joined: false, active: false }) })
  it("uses the mouse as fallback while an active hand keeps priority", () => { const engine = new PalmThunderEngine(1000, 700); engine.configurePlayers(1); engine.setHands([]); engine.setPointer({ x: .7, y: .6 }); expect(engine.state.players[0]).toMatchObject({ x: .7, y: .6, active: true }); engine.setHands([tracked(1, .2, .3)]); engine.setPointer({ x: .9, y: .9 }); expect(engine.state.players[0]).toMatchObject({ x: .2, y: .3, active: true }) })
  it("keeps bomb inventories independent and capped at three", () => { const engine = new PalmThunderEngine(1000, 700); engine.configurePlayers(2); engine.setPhase("playing"); engine.setHands([tracked(1, .4, .8), tracked(2, .6, .8)]); expect(engine.triggerBomb(1)).toBe(true); expect(engine.state.players.map((p) => p.bombs)).toEqual([2, 3]); expect(engine.triggerBomb(1)).toBe(true); expect(engine.triggerBomb(1)).toBe(true); expect(engine.triggerBomb(1)).toBe(false) })
  it("revives a dead teammate in real time without changing phase", () => { const engine = new PalmThunderEngine(1000, 700); engine.configurePlayers(2); engine.setPhase("playing"); engine.setHands([tracked(1, .4, .8), tracked(2, .6, .8)]); const target = engine.state.players[1]!; target.dead = true; target.lives = 0; const elapsed = engine.state.elapsedMs; expect(engine.triggerLove(1)).toBe(true); expect(target).toMatchObject({ dead: false, lives: 1 }); expect(target.invulnerableMs).toBeGreaterThan(2000); expect(engine.state.phase).toBe("playing"); expect(engine.state.elapsedMs).toBe(elapsed) })
  it("spawns bomb gifts with 1-3 bombs", () => { vi.spyOn(Math, "random").mockReturnValue(.4); const engine = new PalmThunderEngine(1000, 700); engine.setPhase("playing"); engine.update(40); (engine as unknown as { giftMs: number }).giftMs = 0; engine.update(40); const gift = engine.state.pickups[0]!; expect(gift.kind).toBe("bomb"); expect(gift.amount).toBeGreaterThanOrEqual(1); expect(gift.amount).toBeLessThanOrEqual(3); vi.restoreAllMocks() })
  it("changes weapon mode through gifts and emits distinct laser shots", () => { const engine = new PalmThunderEngine(1000, 700); engine.configurePlayers(1); engine.setPhase("playing"); engine.setHands([tracked(1, .4, .8)]); engine.state.pickups.push({ id: 999, kind: "weapon", amount: 1, weaponMode: "laser", x: .4, y: .8, vy: 0, radius: .04 }); engine.update(20); expect(engine.state.players[0]!.weaponMode).toBe("laser"); for (let i = 0; i < 4; i++) engine.update(40); expect(engine.state.bullets.some((bullet) => bullet.owner === 1 && bullet.style === "laser")).toBe(true) })
})
