import type { Bullet, Enemy, GameSnapshot, Pickup, Player, TrackedHand } from "./types"

export class ThunderRenderer {
  private ctx: CanvasRenderingContext2D
  constructor(private canvas: HTMLCanvasElement) { const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("Canvas unavailable"); this.ctx = ctx }
  resize(width: number, height: number): void { const scale = Math.min(2, devicePixelRatio || 1); this.canvas.width = Math.round(width * scale); this.canvas.height = Math.round(height * scale); this.canvas.style.width = `${width}px`; this.canvas.style.height = `${height}px`; this.ctx.setTransform(scale, 0, 0, scale, 0, 0) }
  render(s: GameSnapshot, hands: TrackedHand[]): void {
    const { ctx } = this; const w = s.width, h = s.height; ctx.clearRect(0, 0, w, h); ctx.save(); const reduce = matchMedia("(prefers-reduced-motion: reduce)").matches; const shake = reduce ? 0 : s.shake * 12; ctx.translate((Math.random() - .5) * shake, (Math.random() - .5) * shake)
    this.background(s); for (const p of s.pickups) this.pickup(p, w, h, s.elapsedMs); for (const b of s.bullets) this.bullet(b, w, h); for (const e of s.enemies) this.enemy(e, w, h, s.elapsedMs); for (const p of s.players) if (p.joined && !p.dead) this.ship(p, w, h, s.elapsedMs)
    for (const p of s.particles) { ctx.globalAlpha = Math.max(0, p.life / p.maxLife); ctx.fillStyle = p.color; ctx.beginPath(); ctx.arc(p.x * w, p.y * h, p.size, 0, Math.PI * 2); ctx.fill() } ctx.globalAlpha = 1
    if (s.bombWave > 0) { ctx.strokeStyle = `rgba(255,220,120,${s.bombWave})`; ctx.lineWidth = 12; ctx.beginPath(); ctx.arc(w / 2, h / 2, (1 - s.bombWave) * Math.max(w, h), 0, Math.PI * 2); ctx.stroke(); const g = ctx.createRadialGradient(w / 2, h / 2, 10, w / 2, h / 2, Math.max(w, h)); g.addColorStop(.5, "transparent"); g.addColorStop(1, `rgba(255,55,10,${s.bombWave * .8})`); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h) }
    for (const hand of hands) if (hand.active) this.handLock(hand, w, h)
    ctx.restore(); if (s.flash > 0) { ctx.fillStyle = `rgba(255,245,205,${s.flash * .42})`; ctx.fillRect(0, 0, w, h) }
  }
  private background(s: GameSnapshot): void { const { ctx } = this, w = s.width, h = s.height; const g = ctx.createLinearGradient(0, 0, 0, h); g.addColorStop(0, "rgba(5,15,38,.34)"); g.addColorStop(.7, "rgba(3,10,25,.5)"); g.addColorStop(1, "rgba(0,3,12,.72)"); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = "rgba(70,180,255,.12)"; ctx.lineWidth = 1; const offset = (s.elapsedMs * .08) % 80; for (let y = -80 + offset; y < h; y += 80) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke() } }
  private ship(p: Player, w: number, h: number, t: number): void {
    const { ctx } = this, x = p.x * w, y = p.y * h, c = p.id === 1 ? "#37e5ff" : "#ff5fd1", dark = p.id === 1 ? "#075b91" : "#8a1b77"
    ctx.save(); ctx.translate(x, y); if (p.invulnerableMs > 0) { ctx.globalAlpha = .55 + Math.sin(t / 55) * .25; ctx.strokeStyle = c; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(0, 0, 35 + Math.sin(t / 90) * 3, 0, Math.PI * 2); ctx.stroke() }
    const flame = 20 + Math.sin(t / 42) * 7; for (const offset of [-11, 11]) { const fg = ctx.createLinearGradient(offset, 14, offset, 14 + flame); fg.addColorStop(0, "white"); fg.addColorStop(.28, c); fg.addColorStop(1, "transparent"); ctx.fillStyle = fg; ctx.beginPath(); ctx.moveTo(offset - 4, 12); ctx.lineTo(offset, 14 + flame); ctx.lineTo(offset + 4, 12); ctx.fill() }
    ctx.shadowBlur = 20; ctx.shadowColor = c; ctx.fillStyle = dark; ctx.beginPath(); if (p.id === 1) { ctx.moveTo(0, -34); ctx.lineTo(12, -5); ctx.lineTo(32, 14); ctx.lineTo(13, 11); ctx.lineTo(7, 25); ctx.lineTo(0, 19); ctx.lineTo(-7, 25); ctx.lineTo(-13, 11); ctx.lineTo(-32, 14); ctx.lineTo(-12, -5) } else { ctx.moveTo(0, -31); ctx.lineTo(10, -9); ctx.lineTo(29, -1); ctx.lineTo(18, 9); ctx.lineTo(27, 20); ctx.lineTo(8, 15); ctx.lineTo(0, 26); ctx.lineTo(-8, 15); ctx.lineTo(-27, 20); ctx.lineTo(-18, 9); ctx.lineTo(-29, -1); ctx.lineTo(-10, -9) } ctx.closePath(); ctx.fill()
    ctx.lineWidth = 2; ctx.strokeStyle = c; ctx.stroke(); ctx.fillStyle = c; ctx.fillRect(-22, 8, 8, 5); ctx.fillRect(14, 8, 8, 5); ctx.fillStyle = "#eaffff"; ctx.beginPath(); ctx.ellipse(0, -8, 6, 15, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = p.weaponMode === "laser" ? "#8affff" : p.weaponMode === "spread" ? "#ffd84c" : "#fff"; ctx.fillRect(-3, -31, 6, 14); ctx.restore()
  }
  private enemy(e: Enemy, w: number, h: number, t: number): void {
    const { ctx } = this, x = e.x * w, y = e.y * h, r = e.radius * Math.min(w, h), colors: Record<Enemy["kind"], [string, string]> = { scout: ["#b92f4a", "#ff7d55"], interceptor: ["#6f35ae", "#c87bff"], fighter: ["#b64027", "#ffc14b"], bomber: ["#70413a", "#ff8b45"], turret: ["#45616b", "#83e7ff"], elite: ["#8c291d", "#ffe06b"], boss: ["#551223", "#ff4e38"] }
    const [body, glow] = colors[e.kind]; ctx.save(); ctx.translate(x, y); ctx.rotate(e.kind === "boss" ? Math.sin(t / 5000) * .04 : Math.sin(t / 350 + e.phase) * (e.kind === "interceptor" ? .24 : .09)); ctx.shadowBlur = e.kind === "boss" ? 34 : 13; ctx.shadowColor = glow; ctx.fillStyle = body
    ctx.beginPath(); if (e.kind === "bomber") { ctx.ellipse(0, 0, r * 1.15, r * .78, 0, 0, Math.PI * 2); ctx.moveTo(-r * 1.5, 0); ctx.lineTo(-r * .5, -r * .45); ctx.lineTo(-r * .5, r * .45); ctx.closePath(); ctx.moveTo(r * 1.5, 0); ctx.lineTo(r * .5, -r * .45); ctx.lineTo(r * .5, r * .45); ctx.closePath() } else if (e.kind === "turret") { ctx.rect(-r, -r * .65, r * 2, r * 1.3) } else { ctx.moveTo(0, r); ctx.lineTo(r * (e.kind === "boss" ? 1.65 : 1.2), -r * .65); ctx.lineTo(r * .38, -r * .42); ctx.lineTo(0, -r); ctx.lineTo(-r * .38, -r * .42); ctx.lineTo(-r * (e.kind === "boss" ? 1.65 : 1.2), -r * .65); ctx.closePath() } ctx.fill(); ctx.strokeStyle = glow; ctx.lineWidth = Math.max(1.5, r * .08); ctx.stroke()
    ctx.fillStyle = glow; if (e.kind === "turret") { ctx.beginPath(); ctx.arc(0, 0, r * .42, 0, Math.PI * 2); ctx.fill(); ctx.fillRect(-r * .1, 0, r * .2, r) } else { ctx.beginPath(); ctx.ellipse(0, 0, r * .18, r * .45, 0, 0, Math.PI * 2); ctx.fill() } if (e.kind === "boss") { ctx.fillRect(-r * 1.3, -r * .2, r * .5, r * .25); ctx.fillRect(r * .8, -r * .2, r * .5, r * .25) } ctx.restore()
  }
  private bullet(b: Bullet, w: number, h: number): void {
    const { ctx } = this, x = b.x * w, y = b.y * h, palette: Record<Bullet["style"], [string, string]> = { vulcan: ["#eaffff", "#45e7ff"], spread: ["#fff5a0", "#ffb92e"], laser: ["#d5ffff", "#00f6ff"], plasma: ["#ff8df2", "#b52cff"], orb: ["#fff0a1", "#ff3c28"], missile: ["#ffffff", "#ff782e"] }; const [fill, glow] = palette[b.style]; ctx.save(); ctx.translate(x, y); ctx.rotate(Math.atan2(b.vy, b.vx) + Math.PI / 2); ctx.shadowBlur = b.style === "laser" ? 22 : 14; ctx.shadowColor = glow; ctx.fillStyle = fill; ctx.strokeStyle = glow
    if (b.style === "laser") { ctx.fillRect(-3, -20, 6, 40); ctx.globalAlpha = .45; ctx.fillStyle = glow; ctx.fillRect(-7, -25, 14, 50) } else if (b.style === "missile") { ctx.beginPath(); ctx.moveTo(0, -11); ctx.lineTo(6, 7); ctx.lineTo(0, 4); ctx.lineTo(-6, 7); ctx.closePath(); ctx.fill(); ctx.fillStyle = glow; ctx.fillRect(-2, 7, 4, 12) } else if (b.style === "plasma") { ctx.beginPath(); ctx.moveTo(0, -10); ctx.lineTo(8, 0); ctx.lineTo(0, 10); ctx.lineTo(-8, 0); ctx.closePath(); ctx.fill() } else { ctx.beginPath(); ctx.ellipse(0, 0, b.style === "spread" ? 5 : 4, b.owner === 0 ? 8 : 12, 0, 0, Math.PI * 2); ctx.fill() } ctx.restore()
  }
  private pickup(p: Pickup, w: number, h: number, t: number): void { const { ctx } = this, x = p.x * w, y = p.y * h, label = p.kind === "bomb" ? `B${p.amount}` : p.weaponMode === "laser" ? "L" : p.weaponMode === "spread" ? "S" : "V", color = p.kind === "bomb" ? "#ffbd45" : p.weaponMode === "laser" ? "#43efff" : p.weaponMode === "spread" ? "#ffcf45" : "#72ff91"; ctx.save(); ctx.translate(x, y); ctx.rotate(t / 520); ctx.shadowBlur = 22; ctx.shadowColor = color; ctx.fillStyle = "#071629"; ctx.beginPath(); for (let i = 0; i < 8; i++) { const a = Math.PI / 4 * i; const r = i % 2 ? 19 : 23; ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r) } ctx.closePath(); ctx.fill(); ctx.strokeStyle = color; ctx.lineWidth = 3; ctx.stroke(); ctx.rotate(-t / 520); ctx.fillStyle = color; ctx.font = "900 15px system-ui"; ctx.textAlign = "center"; ctx.fillText(label, 0, 6); ctx.restore() }
  private handLock(hand: TrackedHand, w: number, h: number): void { const { ctx } = this, x = hand.center.x * w, y = hand.center.y * h, color = hand.id === 1 ? "#37e5ff" : "#ff5fd1", gesture = { open: "OPEN", fist: "✊ FIST", love: "LOVE", unknown: "SCANNING" }[hand.gesture]; ctx.strokeStyle = color; ctx.lineWidth = 2; ctx.globalAlpha = .75; ctx.beginPath(); ctx.arc(x, y, 35, -.3, 1.1); ctx.arc(x, y, 35, 2.0, 3.45); ctx.stroke(); if (hand.gestureProgress > 0) { ctx.lineWidth = 5; ctx.beginPath(); ctx.arc(x, y, 43, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * hand.gestureProgress); ctx.stroke() } ctx.fillStyle = color; ctx.font = "700 11px system-ui"; ctx.textAlign = "center"; ctx.fillText(`P${hand.id} · ${gesture}`, x, y + 52); ctx.globalAlpha = 1 }
}
