"""Public API for the hugging-mac model SDK."""

from hugging_mac_sdk.converters import ConversionService, ConverterRegistry, ModelConverter
from hugging_mac_sdk.core.config import ModelPackageConfig, load_model_config
from hugging_mac_sdk.core.facade import ModelHandle, ModelSdk
from hugging_mac_sdk.core.instance import BaseModelInstance, ModelInstanceInfo, ModelState
from hugging_mac_sdk.core.manager import InstanceManager, ReusePolicy
from hugging_mac_sdk.core.registry import ModelDefinition, ModelRegistry
from hugging_mac_sdk.core.resources import ModelResourceProvider, ModelResourceService
from hugging_mac_sdk.core.runtime_policy import RuntimePolicy
from hugging_mac_sdk.errors import (
    DownloadError,
    HuggingMacSdkError,
    InferenceError,
    InsufficientResourceError,
    ManifestError,
    ModelLoadError,
    RegistrationConflictError,
    ResourceIntegrityError,
    ResourceNotFoundError,
    UnsupportedCapabilityError,
    UnsupportedRuntimeError,
)
from hugging_mac_sdk.resources import DownloadProgress, ResourceDownloader
from hugging_mac_sdk.runtime import (
    CoreMLProvider,
    CoreMLSession,
    DeviceInfo,
    DeviceKind,
    OnnxRuntimeProvider,
    OnnxRuntimeSession,
    RuntimeAdapter,
    RuntimeBackend,
    RuntimeRegistry,
    RuntimeSession,
    TorchProvider,
    TorchSession,
    create_default_runtime_registry,
)
from hugging_mac_sdk.schemas.artifact import ArtifactKind, ModelArtifact
from hugging_mac_sdk.schemas.catalog import (
    InstanceSnapshot,
    LifecycleMetrics,
    LifecycleOperation,
    ModelCatalogSnapshot,
    ModelSummary,
    RuntimeSummary,
    UnloadResult,
    VariantSummary,
)
from hugging_mac_sdk.schemas.chat import (
    ChatImage,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    ChatStreamEvent,
    ChatTimings,
)
from hugging_mac_sdk.schemas.conversion import (
    ArtifactFormat,
    ConversionRequest,
    ConversionResult,
)
from hugging_mac_sdk.schemas.detection import (
    BoundingBox,
    Detection,
    DetectionRequest,
    DetectionResponse,
    ImageInput,
)
from hugging_mac_sdk.schemas.health import HealthReport, HealthStatus
from hugging_mac_sdk.schemas.manifest import ModelManifest, ModelVariantSpec, RuntimeSpec
from hugging_mac_sdk.schemas.pose import Keypoint, Pose, PoseEstimationResponse, PoseRequest
from hugging_mac_sdk.schemas.resources import (
    CompositeResource,
    CompositeSource,
    ConversionTargetStatus,
    HuggingFaceSource,
    ModelArtifactStatus,
    ModelResourceStatus,
    ResolvedResource,
    RuntimeResourceStatus,
    UrlArchiveSource,
    UrlFileSource,
)
from hugging_mac_sdk.schemas.segmentation import (
    PolygonPoint,
    Segmentation,
    SegmentationRequest,
    SegmentationResponse,
)
from hugging_mac_sdk.schemas.speech_enhancement import (
    SpeechEnhancementRequest,
    SpeechEnhancementResponse,
    SpeechEnhancementTimings,
)
from hugging_mac_sdk.schemas.speech_synthesis import (
    SpeechSynthesisRequest,
    SpeechSynthesisResponse,
    SpeechSynthesisTimings,
)
from hugging_mac_sdk.schemas.speech_understanding import (
    SpeechLanguage,
    SpeechUnderstandingRequest,
    SpeechUnderstandingResponse,
)
from hugging_mac_sdk.schemas.streaming_transcription import (
    StreamingTranscriptionRequest,
    StreamingTranscriptionResponse,
    StreamingTranscriptionSession,
)
from hugging_mac_sdk.schemas.transcription import (
    AudioInput,
    TranscriptionRequest,
    TranscriptionResponse,
    TranscriptionTimings,
)
from hugging_mac_sdk.schemas.voice_activity import (
    SpeechSegment,
    VoiceActivityRequest,
    VoiceActivityResponse,
    VoiceActivityTimings,
)

__all__ = [
    "ArtifactFormat",
    "ArtifactKind",
    "AudioInput",
    "BaseModelInstance",
    "BoundingBox",
    "ChatImage",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamEvent",
    "ChatTimings",
    "CompositeResource",
    "CompositeSource",
    "ConversionRequest",
    "ConversionResult",
    "ConversionService",
    "ConversionTargetStatus",
    "ConverterRegistry",
    "CoreMLProvider",
    "CoreMLSession",
    "Detection",
    "DetectionRequest",
    "DetectionResponse",
    "DeviceInfo",
    "DeviceKind",
    "DownloadError",
    "DownloadProgress",
    "HealthReport",
    "HealthStatus",
    "HuggingFaceSource",
    "HuggingMacSdkError",
    "ImageInput",
    "InferenceError",
    "InstanceManager",
    "InstanceSnapshot",
    "InsufficientResourceError",
    "Keypoint",
    "LifecycleMetrics",
    "LifecycleOperation",
    "ManifestError",
    "ModelArtifact",
    "ModelArtifactStatus",
    "ModelCatalogSnapshot",
    "ModelConverter",
    "ModelDefinition",
    "ModelHandle",
    "ModelInstanceInfo",
    "ModelLoadError",
    "ModelManifest",
    "ModelPackageConfig",
    "ModelRegistry",
    "ModelResourceProvider",
    "ModelResourceService",
    "ModelResourceStatus",
    "ModelSdk",
    "ModelState",
    "ModelSummary",
    "ModelVariantSpec",
    "OnnxRuntimeProvider",
    "OnnxRuntimeSession",
    "PolygonPoint",
    "Pose",
    "PoseEstimationResponse",
    "PoseRequest",
    "RegistrationConflictError",
    "ResolvedResource",
    "ResourceDownloader",
    "ResourceIntegrityError",
    "ResourceNotFoundError",
    "ReusePolicy",
    "RuntimeAdapter",
    "RuntimeBackend",
    "RuntimePolicy",
    "RuntimeRegistry",
    "RuntimeResourceStatus",
    "RuntimeSession",
    "RuntimeSpec",
    "RuntimeSummary",
    "Segmentation",
    "SegmentationRequest",
    "SegmentationResponse",
    "SpeechEnhancementRequest",
    "SpeechEnhancementResponse",
    "SpeechEnhancementTimings",
    "SpeechLanguage",
    "SpeechSegment",
    "SpeechSynthesisRequest",
    "SpeechSynthesisResponse",
    "SpeechSynthesisTimings",
    "SpeechUnderstandingRequest",
    "SpeechUnderstandingResponse",
    "StreamingTranscriptionRequest",
    "StreamingTranscriptionResponse",
    "StreamingTranscriptionSession",
    "TorchProvider",
    "TorchSession",
    "TranscriptionRequest",
    "TranscriptionResponse",
    "TranscriptionTimings",
    "UnloadResult",
    "UnsupportedCapabilityError",
    "UnsupportedRuntimeError",
    "UrlArchiveSource",
    "UrlFileSource",
    "VariantSummary",
    "VoiceActivityRequest",
    "VoiceActivityResponse",
    "VoiceActivityTimings",
    "create_default_runtime_registry",
    "load_model_config",
]
