"""Task-specific capability contracts."""

from hugging_mac_sdk.capabilities.protocols import (
    Chat,
    DocumentLayoutAnalysis,
    DocumentParsing,
    FaceDetection,
    HandDetection,
    ImageEmbedding,
    ImageTextSimilarity,
    InstanceSegmentation,
    ObjectDetection,
    PoseEstimation,
    SpeechEnhancement,
    SpeechSynthesis,
    SpeechTranscription,
    SpeechUnderstanding,
    StreamingSpeechTranscription,
    TextEmbedding,
    VoiceActivityDetection,
)

__all__ = [
    "Chat",
    "DocumentLayoutAnalysis",
    "DocumentParsing",
    "FaceDetection",
    "HandDetection",
    "ImageEmbedding",
    "ImageTextSimilarity",
    "InstanceSegmentation",
    "ObjectDetection",
    "PoseEstimation",
    "SpeechEnhancement",
    "SpeechSynthesis",
    "SpeechTranscription",
    "SpeechUnderstanding",
    "StreamingSpeechTranscription",
    "TextEmbedding",
    "VoiceActivityDetection",
]
